### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gt008** [springfall2008/predai#16]
Hi Tried to install PredAI this morning but does not seem to work. I am seeing the following in the logs. 

Running App Process Management
Your API key is: aa34edcd918da54397ec56166002c217e4cbc88110fde4682e338b58879df9e7061463e9566ba8b6afc720bb4aca30ce2e5a9d302f3c9db3
Bootstrap predai
Copy initial python files
Startup
Importing plotly failed. Interactive plots will not work.
Importing plotly failed. Interactive plots will not work.
HA Interface started key aa34edcd918da54397ec56166002c217e4cbc88110fde4682e338b58879df9e7061463e9566ba8b6afc720bb4aca30ce2e5a9d302f3c9db3 url http://supervisor/core
Traceback (most recent call last):
  File "/config/predai.py", line 427, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/config/predai.py", line 358, in main
    config = yaml.safe_load(open("/config/predai.yaml"))
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 111, in compose_sequence_node

Thanks 

Giles

**Comment by gt008** [comment]
Seems to have been resolved with a restart! Drrr
