### ISSUE TITLE
Error in cpuinfo: prctl(PR_SVE_GET_VL) failed

### ISSUE THREAD

**Issue by heinoskov** [springfall2008/predai#17]
Hello, I installed PredAI on my Home Assistant Blue but gets errors after starting the addon... 

-----------------------------------------------------------
 Add-on: predai
 AI Based time series prediction for Home Assistant
-----------------------------------------------------------
 Add-on version: 1.1.15
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (aarch64 / odroid-n2)
Error in cpuinfo: prctl(PR_SVE_GET_VL) failed
 Home Assistant Core: 2024.10.3
 Home Assistant Supervisor: 2024.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[11:39:49] INFO: Configuring timezone (Europe/Copenhagen)...
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Importing plotly failed. Interactive plots will not work.
Importing plotly failed. Interactive plots will not work.
HA Interface started key a60a810eaf7280bdfea602467fbe9494cfbb8693a78f28e95270ce3ef4ceec14d5439d889f970fa6a974ac233c9bddc4cc1c5e693b347871 url http://supervisor/core
Configuration loaded
Update at time 2024-10-21 11:00:00+02:00 Processing sensor sensor.power_house_load incrementing True max_increment 10 reset_daily True interval 30 days 7 export_days 7 subtract sensor.ev_wallbox_charging_power_in_watts
Getting history for sensor sensor.power_house_load start 2024-10-14T11:00:00+0200 end 2024-10-21T11:00:00+0200
Failed to decode response from http://supervisor/core/api/history/period/2024-10-14T11:00:00+0200
History for sensor sensor.power_house_load starts at 2024-10-14 11:00:00+02:00 ends at 2024-10-21 11:00:00+02:00
Traceback (most recent call last):
  File "/config/predai.py", line 427, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/config/predai.py", line 394, in main
    dataset, start, end = await get_history(interface, nw, sensor_name, now, incrementing, max_increment, days, use_db, reset_low, reset_high)
  File "/config/predai.py", line 341, in get_history
    dataset, last_dataset_value = await nw.process_dataset(sensor_name, dataset, start, end, incrementing=incrementing, max_increment=max_increment, reset_low=reset_low, reset_high=reset_high)
  File "/config/predai.py", line 136, in process_dataset
    data_len = len(new_data)
TypeError: object of type 'NoneType' has no len()
[11:40:00] INFO: PredAI init script running
Running App Process Management
Your API key is: a60a810eaf7280bdfea602467fbe9494cfbb8693a78f28e95270ce3ef4ceec14d5439d889f970fa6a974ac233c9bddc4cc1c5e693b347871
Bootstrap predai
Copy initial python files
Startup

**Comment by springfall2008** [comment]
It appears the sensor you tried to use has no data, maybe a typo in predai.yaml?
