### ISSUE TITLE
ValueError: Provided DataFrame (df) must be of pd.DataFrame type.

### ISSUE THREAD

**Issue by paulgee31** [springfall2008/predai#3]
Hi there,

I've installed Predai  on my HA  which is connected to a GE inverter and Zappi charger. I've configured for 5 day interval at the moment but Predai seems to be suffering a ValueError: Provided DataFrame (df) must be of pd.DataFrame type.

Hope this proves useful but let me know if you require me to alter settings at my end.

Log below:

```
Configuration loaded
Processing sensor sensor.givtcp_xxx_load_energy_total_kwh incrementing True reset_daily True interval 30 days 5 subtract sensor.myenergi_zappi_xxx_charge_added_session
Getting history for sensor sensor.givtcp_xxxxx_load_energy_total_kwh
Making API call to http://supervisor/core/api/history/period/2024-04-10T15:00:00+0100
Response <Response [200]>
Getting history for sensor sensor.myenergi_zappi_xxxxx_charge_added_session
Making API call to http://supervisor/core/api/history/period/2024-04-10T15:00:00+0100
Response <Response [200]>
Processing dataset
                           ds    y
0   2024-04-10 15:00:00+01:00  0.0
1   2024-04-10 15:30:00+01:00  0.4
2   2024-04-10 16:00:00+01:00  0.3
3   2024-04-10 16:30:00+01:00  0.3
4   2024-04-10 17:00:00+01:00  0.3
..                        ...  ...
235 2024-04-15 12:30:00+01:00  0.1
236 2024-04-15 13:00:00+01:00  0.6
237 2024-04-15 13:30:00+01:00  0.1
238 2024-04-15 14:00:00+01:00  0.4
239 2024-04-15 14:30:00+01:00  0.1

[240 rows x 2 columns]
Processing subtract
                           ds    y
0   2024-04-10 15:00:00+01:00  0.0
1   2024-04-10 15:30:00+01:00  0.0
2   2024-04-10 16:00:00+01:00  0.0
3   2024-04-10 16:30:00+01:00  0.0
4   2024-04-10 17:00:00+01:00  0.0
..                        ...  ...
232 2024-04-15 11:00:00+01:00  0.0
233 2024-04-15 11:30:00+01:00  0.0
234 2024-04-15 12:00:00+01:00  0.0
235 2024-04-15 12:30:00+01:00  0.0
236 2024-04-15 13:00:00+01:00  0.0

[237 rows x 2 columns]
Subtracting data
Pruned set:                            ds    y
0   2024-04-10 15:00:00+01:00  0.0
1   2024-04-10 15:30:00+01:00  0.4
2   2024-04-10 16:00:00+01:00  0.3
3   2024-04-10 16:30:00+01:00  0.3
4   2024-04-10 17:00:00+01:00  0.3
..                        ...  ...
235 2024-04-15 12:30:00+01:00  0.1
236 2024-04-15 13:00:00+01:00  0.6
237 2024-04-15 13:30:00+01:00  0.1
238 2024-04-15 14:00:00+01:00  0.4
239 2024-04-15 14:30:00+01:00  0.1

[240 rows x 2 columns]
WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)


Finding best initial lr:   0%|          | 0/213 [00:00<?, ?it/s]
Finding best initial lr:   0%|          | 1/213 [00:00<00:24,  8.77it/s]
Finding best initial lr:   2%|▏         | 4/213 [00:00<00:12, 17.41it/s]
Finding best initial lr:   3%|▎         | 7/213 [00:00<00:10, 20.01it/s]
Finding best initial lr:   5%|▍         | 10/213 [00:00<00:09, 21.20it/s]
Finding best initial lr:   6%|▌         | 13/213 [00:00<00:09, 20.47it/s]
Finding best initial lr:   8%|▊         | 16/213 [00:00<00:09, 20.95it/s]
Finding best initial lr:   9%|▉         | 19/213 [00:00<00:09, 21.05it/s]
Finding best initial lr:  10%|█         | 22/213 [00:01<00:08, 21.56it/s]
Finding best initial lr:  12%|█▏        | 25/213 [00:01<00:08, 21.93it/s]
Finding best initial lr:  13%|█▎        | 28/213 [00:01<00:08, 22.18it/s]
Finding best initial lr:  15%|█▍        | 31/213 [00:01<00:08, 21.97it/s]
Finding best initial lr:  16%|█▌        | 34/213 [00:01<00:08, 22.31it/s]
Finding best initial lr:  17%|█▋        | 37/213 [00:01<00:07, 22.59it/s]
Finding best initial lr:  19%|█▉        | 40/213 [00:01<00:07, 22.37it/s]
Finding best initial lr:  20%|██        | 43/213 [00:02<00:08, 20.73it/s]
Finding best initial lr:  22%|██▏       | 46/213 [00:02<00:07, 21.12it/s]
Finding best initial lr:  23%|██▎       | 49/213 [00:02<00:07, 21.62it/s]
Finding best initial lr:  24%|██▍       | 52/213 [00:02<00:07, 22.07it/s]
Finding best initial lr:  26%|██▌       | 55/213 [00:02<00:07, 22.52it/s]
Finding best initial lr:  27%|██▋       | 58/213 [00:02<00:06, 22.78it/s]
Finding best initial lr:  29%|██▊       | 61/213 [00:02<00:06, 22.65it/s]
Finding best initial lr:  30%|███       | 64/213 [00:02<00:06, 22.74it/s]
Finding best initial lr:  31%|███▏      | 67/213 [00:03<00:06, 22.83it/s]
Finding best initial lr:  33%|███▎      | 70/213 [00:03<00:06, 22.89it/s]
Finding best initial lr:  34%|███▍      | 73/213 [00:03<00:06, 22.87it/s]
Finding best initial lr:  36%|███▌      | 76/213 [00:03<00:05, 24.51it/s]
Finding best initial lr:  38%|███▊      | 80/213 [00:03<00:05, 25.84it/s]
Finding best initial lr:  39%|███▉      | 84/213 [00:03<00:04, 28.04it/s]
Finding best initial lr:  41%|████▏     | 88/213 [00:03<00:04, 29.77it/s]
Finding best initial lr:  43%|████▎     | 91/213 [00:03<00:04, 29.48it/s]
Finding best initial lr:  45%|████▍     | 95/213 [00:04<00:03, 29.83it/s]
Finding best initial lr:  46%|████▌     | 98/213 [00:04<00:03, 28.83it/s]
Finding best initial lr:  47%|████▋     | 101/213 [00:04<00:03, 28.83it/s]
Finding best initial lr:  49%|████▉     | 104/213 [00:04<00:03, 28.80it/s]
Finding best initial lr:  50%|█████     | 107/213 [00:04<00:03, 27.71it/s]
Finding best initial lr:  52%|█████▏    | 110/213 [00:04<00:03, 26.36it/s]
Finding best initial lr:  53%|█████▎    | 113/213 [00:04<00:04, 23.97it/s]
Finding best initial lr:  54%|█████▍    | 116/213 [00:04<00:04, 20.99it/s]
Finding best initial lr:  56%|█████▌    | 119/213 [00:05<00:04, 22.22it/s]
Finding best initial lr:  57%|█████▋    | 122/213 [00:05<00:03, 22.85it/s]
Finding best initial lr:  59%|█████▊    | 125/213 [00:05<00:03, 23.64it/s]
Finding best initial lr:  60%|██████    | 128/213 [00:05<00:03, 23.91it/s]
Finding best initial lr:  62%|██████▏   | 131/213 [00:05<00:03, 23.98it/s]
Finding best initial lr:  63%|██████▎   | 134/213 [00:05<00:03, 24.22it/s]
Finding best initial lr:  64%|██████▍   | 137/213 [00:05<00:03, 23.75it/s]
Finding best initial lr:  66%|██████▌   | 140/213 [00:05<00:03, 24.13it/s]
Finding best initial lr:  67%|██████▋   | 143/213 [00:06<00:02, 23.88it/s]
Finding best initial lr:  69%|██████▊   | 146/213 [00:06<00:02, 23.59it/s]
Finding best initial lr:  70%|██████▉   | 149/213 [00:06<00:02, 23.63it/s]
Finding best initial lr:  71%|███████▏  | 152/213 [00:06<00:02, 22.94it/s]
Finding best initial lr:  73%|███████▎  | 155/213 [00:06<00:02, 22.66it/s]
Finding best initial lr:  74%|███████▍  | 158/213 [00:06<00:02, 22.37it/s]
Finding best initial lr:  76%|███████▌  | 161/213 [00:06<00:02, 22.57it/s]
Finding best initial lr:  77%|███████▋  | 164/213 [00:07<00:02, 22.58it/s]
Finding best initial lr:  78%|███████▊  | 167/213 [00:07<00:02, 22.22it/s]
Finding best initial lr:  80%|███████▉  | 170/213 [00:07<00:01, 22.24it/s]
Finding best initial lr:  81%|████████  | 173/213 [00:07<00:01, 22.56it/s]
Finding best initial lr:  83%|████████▎ | 176/213 [00:07<00:01, 22.82it/s]
Finding best initial lr:  84%|████████▍ | 179/213 [00:07<00:01, 22.62it/s]
Finding best initial lr:  85%|████████▌ | 182/213 [00:07<00:01, 22.06it/s]
Finding best initial lr:  87%|████████▋ | 185/213 [00:07<00:01, 21.91it/s]
Finding best initial lr:  88%|████████▊ | 188/213 [00:08<00:01, 22.07it/s]
Finding best initial lr:  90%|████████▉ | 191/213 [00:08<00:00, 22.14it/s]
Finding best initial lr:  91%|█████████ | 194/213 [00:08<00:00, 22.39it/s]
Finding best initial lr:  92%|█████████▏| 197/213 [00:08<00:00, 21.90it/s]
Finding best initial lr:  94%|█████████▍| 200/213 [00:08<00:00, 22.14it/s]
Finding best initial lr:  95%|█████████▌| 203/213 [00:08<00:00, 22.25it/s]
Finding best initial lr:  97%|█████████▋| 206/213 [00:08<00:00, 22.53it/s]
Finding best initial lr:  98%|█████████▊| 209/213 [00:09<00:00, 22.04it/s]
Finding best initial lr: 100%|█████████▉| 212/213 [00:09<00:00, 22.07it/s]
Finding best initial lr: 100%|██████████| 213/213 [00:09<00:00, 23.10it/s]
WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/data/split.py:273: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, future_df])

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py:1152: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  converted_ds = pd.to_datetime(ds_col, utc=True).view(dtype=np.int64)

                     ds    y     yhat1     trend  season_daily
0   2024-04-10 14:00:00  0.0  0.335622  0.500582     -0.164960
1   2024-04-10 14:30:00  0.4  0.345751  0.499676     -0.153925
2   2024-04-10 15:00:00  0.3  0.348289  0.498769     -0.150480
3   2024-04-10 15:30:00  0.3  0.357080  0.497863     -0.140783
4   2024-04-10 16:00:00  0.3  0.383938  0.496956     -0.113018
..                  ...  ...       ...       ...           ...
331 2024-04-17 11:30:00  NaN  0.431648  0.596397     -0.164749
332 2024-04-17 12:00:00  NaN  0.367677  0.596713     -0.229036
333 2024-04-17 12:30:00  NaN  0.351509  0.597029     -0.245520
334 2024-04-17 13:00:00  NaN  0.372219  0.597345     -0.225126
335 2024-04-17 13:30:00  NaN  0.405630  0.597661     -0.192031

[336 rows x 5 columns]
Saving prediction to sensor.givtcp_xxxxx_load_energy_total_kwh_prediction last_update 2024-04-15 15:00:00+01:00
Making API call to http://supervisor/core/api/states/sensor.givtcp_xxxxx_load_energy_total_kwh_prediction
Response <Response [200]>
Processing sensor sensor.external_temperature incrementing False reset_daily False interval 30 days 5 subtract None
Getting history for sensor sensor.external_temperature
Making API call to http://supervisor/core/api/history/period/2024-04-10T15:00:00+0100
Response <Response [200]>
Traceback (most recent call last):
  File "/config/predai.py", line 267, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/config/predai.py", line 261, in main
    await nw.train(pruned, future_periods)
  File "/config/predai.py", line 141, in train
    self.metrics = self.model.fit(dataset, freq=(str(self.period) + "min"), progress=None)
  File "/usr/local/lib/python3.10/dist-packages/neuralprophet/forecaster.py", line 1015, in fit
    df, _, _, self.id_list = df_utils.prep_or_copy_df(df)
  File "/usr/local/lib/python3.10/dist-packages/neuralprophet/df_utils.py", line 43, in prep_or_copy_df
    raise ValueError("Provided DataFrame (df) must be of pd.DataFrame type.")
ValueError: Provided DataFrame (df) must be of pd.DataFrame type.
```

**Comment by paulgee31** [comment]
User error at my end.
