### ISSUE TITLE
IndexError: list index out of range on startup

### ISSUE THREAD

**Issue by parklife200** [springfall2008/predai#6]
When starting up I get IndexError: list index out of range in the logs  (serials of inverter,  zappi and HA key removed)

Bootstrap predai
Copy initial python files
Startup

-----------------------------------------------------------
 Add-on: predai
 AI Based time series prediction for Home Assistant
-----------------------------------------------------------
 Add-on version: 1.1.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.4.3
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
[14:23:09] INFO: Configuring timezone (Europe/London)...
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Importing plotly failed. Interactive plots will not work.
Importing plotly failed. Interactive plots will not work.
HA Interface started key xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
url http://supervisor/core
Configuration loaded
Processing sensor sensor.givtcp_fxxxx_load_energy_today_kwh incrementing True reset_daily True interval 30 days 14 export_days 14 subtract ssensor.myenergi_zappi_xxxx_energy_used_today
Getting history for sensor sensor.givtcp_fxxxx_load_energy_today_kwh
Making API call to http://supervisor/core/api/history/period/2024-04-09T14:00:00+0100
Response <Response [200]>
History for sensor sensor.givtcp_fxxxx_load_energy_today_kwh starts at 2024-04-13 03:12:00+00:00
                           ds    y
0   2024-04-13 03:12:00+00:00  0.0
1   2024-04-13 03:42:00+00:00  0.4
2   2024-04-13 04:12:00+00:00  0.4
3   2024-04-13 04:42:00+00:00  0.3
4   2024-04-13 05:12:00+00:00  0.3
..                        ...  ...
495 2024-04-23 10:42:00+00:00  0.4
496 2024-04-23 11:12:00+00:00  0.6
497 2024-04-23 11:42:00+00:00  0.5
498 2024-04-23 12:12:00+00:00  0.4
499 2024-04-23 12:42:00+00:00  0.4

[500 rows x 2 columns]
Create table sensor_givtcp_fxxxx_load_energy_today_kwh
Added 500 rows to database table sensor_givtcp_fxxxx_load_energy_today_kwh
Stored dataset in database and retrieved full history from database length 1486
Getting history for sensor ssensor.myenergi_zappi_xxxx_energy_used_today
Making API call to http://supervisor/core/api/history/period/2024-04-09T14:00:00+0100
Response <Response [200]>
History for sensor ssensor.myenergi_zappi_xxxx_energy_used_today starts at 2024-04-09 14:00:00+01:00
Traceback (most recent call last):
  File "/config/predai.py", line 351, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/config/predai.py", line 331, in main
    subtract_data, start, end = await get_history(interface, nw, subtract_name, now, incrementing, days, use_db)
  File "/config/predai.py", line 282, in get_history
    dataset, last_dataset_value = await nw.process_dataset(dataset, start, end, incrementing=incrementing)
  File "/config/predai.py", line 113, in process_dataset
    last_value = float(new_data[0]["state"])
IndexError: list index out of range
[14:23:44] INFO: PredAI init script running
Running App Process Management
Your API key is:

**Comment by parklife200** [comment]
Spotted a typo in my config, sorry!
